### ISSUE TITLE
Pystykkö poistaa ton viimisen mergen?

### ISSUE THREAD

**Issue by AnonyymiHerrasmies** [Apunyymi/ylilauta-userscripts#3]
kävi pieni fiba...

**Comment by Apunyymi** [comment]
Ei tuossa mitään liian henkilökohtaista näkyisi olevan? Mikä on ongelma?

**Comment by ohjelmoija** [comment]
https://github.com/Apunyymi/ylilauta-userscripts/graphs/contributors on siinä vähän henkkoht tietoa

**Comment by Apunyymi** [comment]
Katselin samaa, mutta ajattelin että menkööt mikäli nyymi näin haluaa. Teen nyt kuitenkin itse tuon saman mergen omalta tililtä.

**Comment by jokil** [comment]
Arvostan tätä. Kiitos!

**Comment by AnonyymiHerrasmies** [comment]
Arvostan tätä. Kiitos! Saatana kun täytyy pitää montaa tiliä.

**Comment by ohjelmoija** [comment]
Tuleville projektin koodaajille jotka ei halua käyttää omaa Github-accounttiaan; muistakaa muokata gitin configia.

Tämän projektin kloonaamisen jälkeen projektin kansiossa:
`git config user.name uuden_accountin_nimi`
`git config user.email uuden_accountin_email`

**Comment by Apunyymi** [comment]
Ilmoitan vain että origin pushattu masteriin. Voisin muuten lisätä tuon @ohjelmoija'n ohjeen README'hen.
